"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { Baby, CalendarDays, ChevronRight, CircleHelp, Edit3, Ellipsis, Plus, Ruler, Scale, Trash2 } from "lucide-react";
import { Area, CartesianGrid, ComposedChart, Legend, Line, ResponsiveContainer, Scatter, Tooltip, XAxis, YAxis } from "recharts";
import { toast } from "sonner";
import { Toaster } from "@/components/ui/sonner";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from "@/components/ui/alert-dialog";
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from "@/components/ui/dropdown-menu";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Tabs, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { growthData } from "./growth-data";

type Child={id:string;name:string;birthDate:string;sex:"male"|"female";createdAt?:string};
type Measurement={id:string;childId:string;measuredAt:string;weightGrams:number|null;heightMm:number|null;headMm:number|null;notes:string;createdAt?:string};
type Metric="weight"|"height"|"head";
type ChartRange="auto"|"6"|"12"|"24"|"60";
const metricMeta={weight:{label:"Peso",unit:"kg",field:"weightGrams" as const,div:1000,icon:Scale,color:"#f06449"},height:{label:"Estatura",unit:"cm",field:"heightMm" as const,div:10,icon:Ruler,color:"#087f8c"},head:{label:"Cabeza",unit:"cm",field:"headMm" as const,div:10,icon:Baby,color:"#8b6fc0"}};
const today=()=>new Date().toISOString().slice(0,10);
const API_BASE=process.env.NEXT_PUBLIC_BASE_PATH??"";
const api=(path:string)=>`${API_BASE}${path}`;
const monthsBetween=(birth:string,date:string)=>(new Date(date+"T12:00:00").getTime()-new Date(birth+"T12:00:00").getTime())/(1000*60*60*24*30.4375);
function ageText(birth:string){const m=Math.max(0,Math.floor(monthsBetween(birth,today())));return m<24?`${m} ${m===1?"mes":"meses"}`:`${Math.floor(m/12)} años y ${m%12} meses`}
function dateText(date:string){return new Intl.DateTimeFormat("es-ES",{day:"numeric",month:"short",year:"numeric"}).format(new Date(date+"T12:00:00"))}
function percentile(point:{l:number;m:number;s:number},value:number){const z=point.l===0?Math.log(value/point.m)/point.s:(Math.pow(value/point.m,point.l)-1)/(point.l*point.s);const t=1/(1+0.2316419*Math.abs(z));const d=0.3989423*Math.exp(-z*z/2);let p=1-d*t*(0.3193815+t*(-0.3565638+t*(1.781478+t*(-1.821256+t*1.330274))));if(z<0)p=1-p;return Math.max(1,Math.min(99,Math.round(p*100)))}
function growthLmsAtAge(points:{l:number;m:number;s:number}[],month:number){const bounded=Math.max(0,Math.min(points.length-1,month)),from=Math.floor(bounded),to=Math.ceil(bounded),ratio=bounded-from,a=points[from],b=points[to];return{l:a.l+(b.l-a.l)*ratio,m:a.m+(b.m-a.m)*ratio,s:a.s+(b.s-a.s)*ratio}}

export default function GrowthApp(){
 const[children,setChildren]=useState<Child[]>([]),[measurements,setMeasurements]=useState<Measurement[]>([]),[selectedId,setSelectedId]=useState(""),[loading,setLoading]=useState(true),[error,setError]=useState("");
 const[metric,setMetric]=useState<Metric>("weight"),[chartRange,setChartRange]=useState<ChartRange>("auto"),[childOpen,setChildOpen]=useState(false),[measureOpen,setMeasureOpen]=useState(false),[editingChild,setEditingChild]=useState<Child|null>(null),[editingMeasure,setEditingMeasure]=useState<Measurement|null>(null),[deleteTarget,setDeleteTarget]=useState<{kind:"child"|"measure";id:string;name:string}|null>(null);
 const fetchData=useCallback(async()=>{try{setError("");const res=await fetch(api("/api/children"),{cache:"no-store"});const data=await res.json();if(!res.ok)throw new Error(data.error);setChildren(data.children);setMeasurements(data.measurements);setSelectedId(v=>data.children.some((c:Child)=>c.id===v)?v:(data.children[0]?.id??""));}catch(e){setError(e instanceof Error?e.message:"No se han podido cargar los datos.")}finally{setLoading(false)}},[]);
 useEffect(()=>{void fetchData()},[fetchData]);
 useEffect(()=>{const context=(document as Document&{modelContext?:{registerTool:(tool:unknown,opts?:{signal?:AbortSignal})=>void|Promise<void>}}).modelContext;if(!context?.registerTool)return;const ctrl=new AbortController();const register=(tool:unknown)=>Promise.resolve(context.registerTool(tool,{signal:ctrl.signal})).catch(()=>{});void register({name:"list_growth_records",title:"Consultar registros",description:"Lista los niños y sus medidas de crecimiento visibles en la aplicación.",inputSchema:{type:"object",properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute:async()=>{const r=await fetch(api("/api/children"));if(!r.ok)throw new Error("No se pudieron consultar los registros");return r.json()}});void register({name:"add_child",title:"Añadir niño",description:"Crea un perfil infantil con nombre, fecha de nacimiento y sexo para sus curvas de referencia.",inputSchema:{type:"object",properties:{name:{type:"string"},birthDate:{type:"string",description:"Fecha AAAA-MM-DD"},sex:{type:"string",enum:["male","female"]}},required:["name","birthDate","sex"],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:async(input:unknown)=>{const r=await fetch(api("/api/children"),{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(input)});const out=await r.json();if(!r.ok)throw new Error(out.error);await fetchData();return out}});void register({name:"add_growth_measurement",title:"Añadir medida",description:"Añade una fecha de control y uno o varios valores de peso, estatura o perímetro craneal.",inputSchema:{type:"object",properties:{childId:{type:"string"},measuredAt:{type:"string"},weight:{type:"number"},height:{type:"number"},head:{type:"number"},notes:{type:"string"}},required:["childId","measuredAt"],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:async(input:unknown)=>{const r=await fetch(api("/api/measurements"),{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(input)});const out=await r.json();if(!r.ok)throw new Error(out.error);await fetchData();return out}});return()=>ctrl.abort()},[fetchData]);
 const child=children.find(c=>c.id===selectedId)??null;
 const records=useMemo(()=>measurements.filter(m=>m.childId===selectedId).sort((a,b)=>b.measuredAt.localeCompare(a.measuredAt)),[measurements,selectedId]);
 const meta=metricMeta[metric];
 const allActual=useMemo(()=>child?records.map(r=>({month:+monthsBetween(child.birthDate,r.measuredAt).toFixed(2),value:r[meta.field]==null?null:(r[meta.field] as number)/meta.div,date:r.measuredAt})).filter(x=>x.value!=null&&x.month>=0&&x.month<=60):[],[child,records,meta]);
 const autoRange=allActual.length?Math.min(60,Math.max(6,Math.ceil((Math.max(...allActual.map(x=>x.month))+2)/3)*3)):6;
 const visibleMonths=chartRange==="auto"?autoRange:Number(chartRange);
 const chartPoints=child?growthData[child.sex][metric].filter(point=>point.month<=visibleMonths):[];
 const actual=allActual.filter(point=>point.month<=visibleMonths);
 const tickStep=visibleMonths<=6?1:visibleMonths<=12?3:visibleMonths<=36?6:12;
 const xTicks=Array.from({length:Math.floor(visibleMonths/tickStep)+1},(_,index)=>index*tickStep);
 const formatAgeTick=(value:number)=>value===0?"Nac.":value<12?`${value} m`:value%12===0?`${value/12} a`:`${Math.floor(value/12)}a ${value%12}m`;
 const latest=(m:Metric)=>{const mm=metricMeta[m];const r=records.find(x=>x[mm.field]!=null);if(!r)return null;const value=(r[mm.field] as number)/mm.div;const month=Math.max(0,Math.min(60,monthsBetween(child!.birthDate,r.measuredAt)));const p=percentile(growthLmsAtAge(growthData[child!.sex][m],month),value);return{value:value.toLocaleString("es-ES",{maximumFractionDigits:1}),date:r.measuredAt,p}};
 const openNewChild=()=>{setEditingChild(null);setChildOpen(true)},openEditChild=()=>{setEditingChild(child);setChildOpen(true)},openNewMeasure=()=>{setEditingMeasure(null);setMeasureOpen(true)};
 async function saveChild(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const fd=new FormData(e.currentTarget);const payload={name:String(fd.get("name")),birthDate:String(fd.get("birthDate")),sex:String(fd.get("sex"))};const url=api(editingChild?`/api/children/${editingChild.id}`:"/api/children");const res=await fetch(url,{method:editingChild?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const out=await res.json();if(!res.ok){toast.error(out.error);return}setChildOpen(false);await fetchData();if(!editingChild)setSelectedId(out.child.id);toast.success(editingChild?"Perfil actualizado":"Perfil creado")}
 async function saveMeasure(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const fd=new FormData(e.currentTarget);const payload={childId:selectedId,measuredAt:String(fd.get("measuredAt")),weight:fd.get("weight"),height:fd.get("height"),head:fd.get("head"),notes:String(fd.get("notes")??"")};const url=api(editingMeasure?`/api/measurements/${editingMeasure.id}`:"/api/measurements");const res=await fetch(url,{method:editingMeasure?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const out=await res.json();if(!res.ok){toast.error(out.error);return}setMeasureOpen(false);await fetchData();toast.success(editingMeasure?"Medida actualizada":"Medida añadida")}
 async function confirmDelete(){if(!deleteTarget)return;const url=api(deleteTarget.kind==="child"?`/api/children/${deleteTarget.id}`:`/api/measurements/${deleteTarget.id}`);const res=await fetch(url,{method:"DELETE"});if(!res.ok){toast.error("No se ha podido eliminar.");return}setDeleteTarget(null);await fetchData();toast.success(deleteTarget.kind==="child"?"Perfil eliminado":"Medida eliminada")}
 if(loading)return <div className="grid min-h-screen place-items-center bg-[#f6f8fb] text-[#547086]">Cargando el cuaderno…</div>;
 return <main className="min-h-screen bg-[#f6f8fb] text-[#17324d]"><Toaster richColors position="top-center"/>
  <header className="sticky top-0 z-30 border-b border-[#dfe8ef] bg-white/90 px-4 py-3 backdrop-blur md:px-8"><div className="mx-auto flex max-w-7xl items-center justify-between gap-4"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-2xl bg-[#087f8c] text-white"><Baby/></span><div><p className="font-display text-xl font-bold leading-tight">Nuevas nutrias</p><p className="hidden text-sm text-[#64788b] sm:block">Crecimiento, paso a paso</p></div></div><Button variant="outline" className="rounded-xl" onClick={openNewChild}><Plus/> Añadir niño</Button></div></header>
  <div className="mx-auto grid max-w-7xl gap-6 px-4 py-6 md:grid-cols-[245px_minmax(0,1fr)] md:px-8">
   <aside className="h-fit rounded-3xl bg-[#103f5c] p-4 text-white shadow-xl shadow-[#103f5c]/10 md:sticky md:top-24"><div className="mb-3 flex items-center justify-between px-2"><p className="text-xs font-bold tracking-widest text-[#9ec8d1]">MIS PEQUEÑOS</p><button aria-label="Añadir perfil" onClick={openNewChild} className="grid size-8 place-items-center rounded-full bg-white/10"><Plus size={17}/></button></div><div className="flex gap-2 overflow-x-auto md:block md:space-y-2">{children.map(c=><button key={c.id} onClick={()=>setSelectedId(c.id)} className={`flex min-w-44 items-center gap-3 rounded-2xl p-3 text-left transition md:w-full ${c.id===selectedId?"bg-white/14 shadow-inner":"hover:bg-white/8"}`}><span className={`grid size-10 shrink-0 place-items-center rounded-full font-bold ${c.sex==="female"?"bg-[#f5b6c5] text-[#713044]":"bg-[#ffcf70] text-[#754e00]"}`}>{c.name[0]?.toUpperCase()}</span><span className="min-w-0"><strong className="block truncate">{c.name}</strong><small className="text-[#cfe1e6]">{ageText(c.birthDate)}</small></span><ChevronRight size={16} className="ml-auto opacity-60"/></button>)}</div>{children.length>0&&<button onClick={openNewChild} className="mt-4 hidden items-center gap-2 px-2 text-sm font-semibold text-[#cfe1e6] md:flex"><Plus size={17}/> Nuevo perfil</button>}</aside>
   {!child?<EmptyState onAdd={openNewChild} error={error}/>:<section className="min-w-0"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-bold tracking-wide text-[#087f8c]">RESUMEN DE {child.name.toUpperCase()}</p><h1 className="font-display mt-1 text-3xl font-bold">Su crecimiento</h1><p className="mt-1 text-sm text-[#6f8395]">{child.sex==="female"?"Niña":"Niño"} · Nació el {dateText(child.birthDate)}</p></div><div className="flex gap-2"><Button variant="outline" size="icon" className="rounded-xl" aria-label="Editar perfil" onClick={openEditChild}><Edit3/></Button><Button className="h-11 rounded-2xl bg-[#f06449] px-5 font-bold hover:bg-[#d9573f]" onClick={openNewMeasure}><Plus/> Nueva medida</Button></div></div>
    {error&&<div className="mt-5 rounded-2xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div>}
    <div className="mt-6 grid gap-4 sm:grid-cols-3">{(["weight","height","head"] as Metric[]).map(k=>{const mm=metricMeta[k],v=latest(k),Icon=mm.icon;return <article key={k} className="rounded-3xl border border-[#dfe8ef] bg-white p-5 shadow-sm"><div className="mb-5 flex items-center justify-between"><span className="text-sm font-bold text-[#64788b]">{mm.label}</span><span className="grid size-9 place-items-center rounded-xl bg-[#edf7f7] text-[#087f8c]"><Icon size={19}/></span></div>{v?<><div className="flex items-end gap-2"><strong className="font-display text-3xl">{v.value} {mm.unit}</strong><span className="mb-1 rounded-full bg-[#fff3dc] px-2 py-0.5 text-xs font-bold text-[#8b5b00]">P{v.p}</span></div><p className="mt-1 text-sm text-[#7a8c9c]">{dateText(v.date)}</p></>:<><strong className="font-display text-2xl text-[#8293a1]">Sin datos</strong><button onClick={openNewMeasure} className="mt-2 block text-sm font-bold text-[#087f8c]">Añadir medida</button></>}</article>})}</div>
    <article className="mt-6 rounded-3xl border border-[#dfe8ef] bg-white p-4 shadow-sm sm:p-6"><div className="flex flex-wrap items-center justify-between gap-4"><div><h2 className="font-display text-xl font-bold">{metricMeta[metric].label} para la edad</h2><p className="text-sm text-[#708496]">Curvas percentilares OMS · mostrando hasta {visibleMonths<12?`${visibleMonths} meses`:formatAgeTick(visibleMonths)}</p></div><div className="flex flex-wrap items-center gap-2"><Tabs value={metric} onValueChange={v=>setMetric(v as Metric)}><TabsList className="rounded-xl bg-[#eef3f6]">{(["weight","height","head"] as Metric[]).map(k=><TabsTrigger key={k} value={k} className="rounded-lg">{metricMeta[k].label}</TabsTrigger>)}</TabsList></Tabs><Select value={chartRange} onValueChange={v=>setChartRange(v as ChartRange)}><SelectTrigger className="w-[158px] rounded-xl" aria-label="Rango de edad de la gráfica"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="auto">Vista automática</SelectItem><SelectItem value="6">Hasta 6 meses</SelectItem><SelectItem value="12">Hasta 1 año</SelectItem><SelectItem value="24">Hasta 2 años</SelectItem><SelectItem value="60">Hasta 5 años</SelectItem></SelectContent></Select></div></div>
     <div className="mt-5 h-[340px] w-full"><ResponsiveContainer width="100%" height="100%"><ComposedChart data={chartPoints} margin={{top:10,right:12,left:-12,bottom:8}}><defs><linearGradient id="percentileBand" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#d8f0ed" stopOpacity=".9"/><stop offset="1" stopColor="#fff2db" stopOpacity=".35"/></linearGradient></defs><CartesianGrid stroke="#e6edf2" strokeDasharray="4 5"/><XAxis dataKey="month" type="number" domain={[0,visibleMonths]} ticks={xTicks} tickFormatter={formatAgeTick} tick={{fontSize:12,fill:"#6f8395"}}/><YAxis domain={["auto","auto"]} tick={{fontSize:12,fill:"#6f8395"}} unit={` ${meta.unit}`} width={54}/><Tooltip formatter={(value,name)=>[`${Number(value).toLocaleString("es-ES",{maximumFractionDigits:1})} ${meta.unit}`,name==="value"?child.name:String(name).toUpperCase()]} labelFormatter={v=>`Edad: ${Math.round(Number(v))} meses`} contentStyle={{borderRadius:16,border:"1px solid #dfe8ef"}}/><Area type="monotone" dataKey="p97" stroke="none" fill="url(#percentileBand)" name="P97"/><Area type="monotone" dataKey="p3" stroke="none" fill="#fff" name="P3"/><Line type="monotone" dataKey="p3" dot={false} stroke="#efb3a7" strokeWidth={1.4} name="P3"/><Line type="monotone" dataKey="p15" dot={false} stroke="#e6bb72" strokeWidth={1.4} name="P15"/><Line type="monotone" dataKey="p50" dot={false} stroke="#4a9ca3" strokeWidth={2} name="P50"/><Line type="monotone" dataKey="p85" dot={false} stroke="#e6bb72" strokeWidth={1.4} name="P85"/><Line type="monotone" dataKey="p97" dot={false} stroke="#efb3a7" strokeWidth={1.4} name="P97"/><Scatter data={actual} dataKey="value" name={child.name} fill={meta.color} line={{stroke:meta.color,strokeWidth:3}} shape="circle"/><Legend iconType="plainline" wrapperStyle={{fontSize:12,paddingTop:8}}/></ComposedChart></ResponsiveContainer></div>
     <p className="mt-3 flex gap-2 rounded-2xl bg-[#f3f7f9] p-3 text-xs leading-relaxed text-[#5e7487]"><CircleHelp size={16} className="mt-0.5 shrink-0"/>Las curvas son una referencia orientativa. Importa especialmente la evolución en el tiempo; consulta con pediatría ante cambios o dudas.</p>
    </article>
    <section className="mt-6"><div className="mb-3 flex items-center justify-between"><h2 className="font-display text-xl font-bold">Historial de medidas</h2><span className="text-sm text-[#708496]">{records.length} {records.length===1?"registro":"registros"}</span></div>{records.length===0?<div className="rounded-3xl border border-dashed border-[#bfd0db] bg-white p-8 text-center"><CalendarDays className="mx-auto text-[#87a4b5]"/><p className="mt-3 font-bold">Todavía no hay medidas</p><p className="mt-1 text-sm text-[#708496]">Añade el primer control para empezar a dibujar sus curvas.</p><Button className="mt-4 rounded-xl" onClick={openNewMeasure}><Plus/> Añadir medida</Button></div>:<div className="overflow-hidden rounded-3xl border border-[#dfe8ef] bg-white">{records.map((r,i)=><div key={r.id} className={`grid grid-cols-[1fr_auto] gap-3 p-4 sm:grid-cols-[170px_1fr_auto] sm:items-center ${i?"border-t border-[#e8eef2]":""}`}><div><strong className="text-sm">{dateText(r.measuredAt)}</strong><p className="text-xs text-[#7a8c9c]">{Math.max(0,Math.round(monthsBetween(child.birthDate,r.measuredAt)))} meses</p></div><div className="col-span-2 flex flex-wrap gap-x-5 gap-y-1 text-sm sm:col-span-1">{r.weightGrams&&<span><b>{(r.weightGrams/1000).toLocaleString("es-ES")} kg</b> peso</span>}{r.heightMm&&<span><b>{(r.heightMm/10).toLocaleString("es-ES")} cm</b> talla</span>}{r.headMm&&<span><b>{(r.headMm/10).toLocaleString("es-ES")} cm</b> cabeza</span>}{r.notes&&<span className="w-full text-xs text-[#6f8395]">{r.notes}</span>}</div><DropdownMenu><DropdownMenuTrigger asChild><Button variant="ghost" size="icon" aria-label="Acciones de la medida"><Ellipsis/></Button></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuItem onClick={()=>{setEditingMeasure(r);setMeasureOpen(true)}}><Edit3/> Editar</DropdownMenuItem><DropdownMenuItem className="text-red-600" onClick={()=>setDeleteTarget({kind:"measure",id:r.id,name:dateText(r.measuredAt)})}><Trash2/> Eliminar</DropdownMenuItem></DropdownMenuContent></DropdownMenu></div>)}</div>}</section>
    <footer className="mt-8 pb-4 text-xs leading-relaxed text-[#718596]">Referencias: <a className="font-bold underline" target="_blank" rel="noreferrer" href="https://www.who.int/tools/child-growth-standards">Estándares de crecimiento infantil de la OMS</a>, aplicables de 0 a 5 años. Los percentiles no sustituyen la valoración profesional.</footer>
   </section>}
  </div>
  <ChildDialog open={childOpen} setOpen={setChildOpen} child={editingChild} onSave={saveChild} onDelete={c=>{setChildOpen(false);setDeleteTarget({kind:"child",id:c.id,name:c.name})}}/>
  {child&&<MeasureDialog key={editingMeasure?.id??"new"} open={measureOpen} setOpen={setMeasureOpen} child={child} record={editingMeasure} onSave={saveMeasure}/>} 
  <AlertDialog open={!!deleteTarget} onOpenChange={o=>!o&&setDeleteTarget(null)}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>¿Eliminar {deleteTarget?.kind==="child"?`el perfil de ${deleteTarget.name}`:"esta medida"}?</AlertDialogTitle><AlertDialogDescription>{deleteTarget?.kind==="child"?"También se borrará todo su historial. Esta acción no se puede deshacer.":"Este registro desaparecerá de las gráficas y del historial."}</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Cancelar</AlertDialogCancel><AlertDialogAction variant="destructive" onClick={confirmDelete}>Eliminar</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </main>
}

function EmptyState({onAdd,error}:{onAdd:()=>void;error:string}){return <section className="grid min-h-[65vh] place-items-center rounded-3xl border border-dashed border-[#bfd0db] bg-white p-8 text-center"><div><span className="mx-auto grid size-20 place-items-center rounded-full bg-[#dff3f1] text-[#087f8c]"><Baby size={38}/></span><h1 className="font-display mt-5 text-3xl font-bold">Empieza con un perfil</h1><p className="mx-auto mt-2 max-w-md text-[#6f8395]">Añade a tu pequeño para registrar peso, estatura y perímetro craneal en su propio cuaderno.</p>{error&&<p className="mt-3 text-sm text-red-600">{error}</p>}<Button className="mt-6 h-11 rounded-xl px-6" onClick={onAdd}><Plus/> Añadir niño</Button></div></section>}
function ChildDialog({open,setOpen,child,onSave,onDelete}:{open:boolean;setOpen:(v:boolean)=>void;child:Child|null;onSave:(e:React.FormEvent<HTMLFormElement>)=>void;onDelete:(c:Child)=>void}){return <Dialog open={open} onOpenChange={setOpen}><DialogContent className="rounded-3xl"><DialogHeader><DialogTitle className="font-display text-2xl">{child?"Editar perfil":"Nuevo pequeño"}</DialogTitle><DialogDescription>Estos datos permiten elegir las curvas de referencia correctas.</DialogDescription></DialogHeader><form onSubmit={onSave} className="space-y-4"><div className="space-y-2"><Label htmlFor="child-name">Nombre</Label><Input id="child-name" name="name" defaultValue={child?.name} required autoFocus placeholder="Por ejemplo, Leo"/></div><div className="space-y-2"><Label htmlFor="birth-date">Fecha de nacimiento</Label><Input id="birth-date" name="birthDate" type="date" max={today()} defaultValue={child?.birthDate} required/></div><div className="space-y-2"><Label>Sexo para la curva de crecimiento</Label><Select name="sex" defaultValue={child?.sex??"male"}><SelectTrigger className="w-full"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="male">Niño</SelectItem><SelectItem value="female">Niña</SelectItem></SelectContent></Select></div><DialogFooter className="pt-2">{child&&<Button type="button" variant="ghost" className="mr-auto text-red-600" onClick={()=>onDelete(child)}><Trash2/> Eliminar perfil</Button>}<Button type="button" variant="outline" onClick={()=>setOpen(false)}>Cancelar</Button><Button type="submit">{child?"Guardar cambios":"Crear perfil"}</Button></DialogFooter></form></DialogContent></Dialog>}
function MeasureDialog({open,setOpen,child,record,onSave}:{open:boolean;setOpen:(v:boolean)=>void;child:Child;record:Measurement|null;onSave:(e:React.FormEvent<HTMLFormElement>)=>void}){return <Dialog open={open} onOpenChange={setOpen}><DialogContent className="max-h-[92vh] overflow-y-auto rounded-3xl"><DialogHeader><DialogTitle className="font-display text-2xl">{record?"Editar medida":`Nueva medida de ${child.name}`}</DialogTitle><DialogDescription>Puedes registrar una, dos o las tres medidas en el mismo control.</DialogDescription></DialogHeader><form onSubmit={onSave} className="space-y-4"><div className="space-y-2"><Label htmlFor="measured-at">Fecha del control</Label><Input id="measured-at" name="measuredAt" type="date" min={child.birthDate} max={today()} defaultValue={record?.measuredAt??today()} required/></div><div className="grid gap-4 sm:grid-cols-3"><div className="space-y-2"><Label htmlFor="weight">Peso · kg</Label><Input id="weight" name="weight" type="number" inputMode="decimal" min="0.5" max="40" step="0.001" defaultValue={record?.weightGrams?record.weightGrams/1000:""} placeholder="8,250"/></div><div className="space-y-2"><Label htmlFor="height">Estatura · cm</Label><Input id="height" name="height" type="number" inputMode="decimal" min="30" max="140" step="0.1" defaultValue={record?.heightMm?record.heightMm/10:""} placeholder="70,2"/></div><div className="space-y-2"><Label htmlFor="head">Cabeza · cm</Label><Input id="head" name="head" type="number" inputMode="decimal" min="20" max="65" step="0.1" defaultValue={record?.headMm?record.headMm/10:""} placeholder="44,1"/></div></div><div className="space-y-2"><Label htmlFor="notes">Notas opcionales</Label><Textarea id="notes" name="notes" defaultValue={record?.notes} placeholder="Visita, observaciones…" maxLength={300}/></div><DialogFooter><Button type="button" variant="outline" onClick={()=>setOpen(false)}>Cancelar</Button><Button type="submit">{record?"Guardar cambios":"Añadir medida"}</Button></DialogFooter></form></DialogContent></Dialog>}
